0131

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -1,13 +1,13 @@
 name: Eslint
 
-# on: [push]
-on: 
-  push:
-    branches:
-      - master
+on: [pull_request]
+# on: 
+#   push:
+#     branches:
+#       - master
       
 jobs:
-    esLint:
+    ESLint:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout
@@ -15,38 +15,33 @@ jobs:
             - name: Set up Node.js
               uses: actions/setup-node@v4
               with:
-                node-version: "16"
+                node-version: "20"
                 cache: "npm"
-            # - name: Create annotation for build error  
-            #   run: echo "::error file=app.js,line=1::Missing semicolon"
             - name: Install dependenies
               run: npm install
-            # - name: npm run lint
-            #   run: npm run lint
-            - name: Run eslint and log reports
-              id: log-eslint-report
-              run: |
-                npm run lint:ci --silent || true
-                reports=$(cat ./reports.txt) 
-                if [ "$reports" == "" ]
-                then
-                    echo '✅ All Passed'
-                    echo "results=✅ All Passed" >> "$GITHUB_OUTPUT"
+            - name: Run ESLint
+              id: lint_and_report
+              continue-on-error: true
+              run: npm run lint:ci --silent > ./lint-reports.txt
+            - name: Log reports and check outcome
+              run: |  
+                echo outcome: ${{ steps.lint_and_report.outcome }}
+                if [[ "${{ steps.lint_and_report.outcome }}" == 'success' ]]; then
+                  echo '✅ All Passed' > ./lint-reports.txt
                 else
-                    echo '😡😡😡😡😡 Error occurred....' 
-                    echo "results=😡😡😡😡😡 Error occurred...." >> "$GITHUB_OUTPUT"
+                  echo '😡😡😡😡😡 Error....' >> ./lint-reports.txt
                 fi
-            - name: Print reports
-              run: |
-                echo ${{ steps.log-eslint-report.outputs.results}}
-                echo reports2=$(cat ./reports.txt) 
-                echo $reports2
-            # - name: Simulate a failure
-            #   id: simulate_failure
-            #   run: exit 1  # Simulate a failure
-            #   continue-on-error: true  # Continue to the next step even if this step fails
-            # - name: Check simulate outcome
-            #   run: |
-            #     echo simulate_failure: ${{ steps.simulate_failure.outcome }}
-
-
+            - name: Save ESLint result
+              uses: actions/upload-artifact@v4
+              id: artifact-upload-step
+              with:
+                name: lint-reports
+                path: ./lint-reports.txt
+            - name: Log reports and check outcome
+              run: |  
+                echo outcome: ${{ steps.lint_and_report.outcome }}
+                if [[ "${{ steps.lint_and_report.outcome }}" == 'success' ]]; then
+                  exit 0
+                else
+                  exit 1
+                fi
